PATH_DATA = './data'
PATH_RESULTS = './results'

COMPANYS = [
    'APPLE',
    'TESLA',
    'MICROSOFT',
    'FORD',
    'CITIGROUP',
    'FREEPORT-MCMORAN',
    'BANK_OF_AMERICA',
    'COCA-COLA',
    'INTEL',
    'GM',
    'AMERICAN_AIRLS',
    'NORWEGIAN_CRUISE',
    'JPMORGAN',
    'PFIZER',
    'MORGAN_STANLEY',
    'DELTA_AIR_LINES',
    'NEWMONT',
    'GE',
    'CISCO'
]

# COMPANYS_TRAIN = [''] # PARA CASOS ONDE QUER TREINAR COM UMA AÇÃO E TESTAR COM OUTRA
# COMPANYS_TEST = [''] # PARA CASOS ONDE QUER TREINAR COM UMA AÇÃO E TESTAR COM OUTRA

